version: '3.8'

networks:
  marklogicDHF:
    driver: bridge
    name: marklogicDHF

services:
  marklogic:
    image: "marklogic:${mlVersion}-installed"
    ports:
        - ${mlHealthPort}:${mlHealthPort}
        - ${mlForeignBindPort}:${mlForeignBindPort}
        - ${mlBindPort}:${mlBindPort}
        - ${mlServicesPort}:${mlServicesPort}
        - ${mlAdminPort}:${mlAdminPort}
        - ${mlManagePort}:${mlManagePort}
        - ${mlAppPorts}:${mlAppPorts}
    hostname: "${mlHost}"
    container_name: "${mlHost}"
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=${mlAdmin}
      - MARKLOGIC_ADMIN_PASSWORD=${mlPassword}
      - TZ=Europe/Prague
    volumes:
      - ./logs/${mlHost}:/var/opt/MarkLogic/Logs
      - ${dataFolder}:/data
    networks:
      - marklogicDHF
